In [1]:
import numpy as np

In [2]:
arr1=np.array([-2,3,-34,56,78,-90,8,3,4,5,6])

In [3]:
arr1

array([ -2,   3, -34,  56,  78, -90,   8,   3,   4,   5,   6])

In [7]:
b=np.sort(arr1)

In [8]:
arr1

array([ -2,   3, -34,  56,  78, -90,   8,   3,   4,   5,   6])

In [9]:
b

array([-90, -34,  -2,   3,   3,   4,   5,   6,   8,  56,  78])

In [10]:
arr1.sort()

In [11]:
arr1

array([-90, -34,  -2,   3,   3,   4,   5,   6,   8,  56,  78])

In [12]:
arr2=np.array([ -2,   3, -34,  56,  78, -90,   8,   3,   4,   5,   6])

In [13]:
np.argsort(arr2)

array([ 5,  2,  0,  1,  7,  8,  9, 10,  6,  3,  4])