In [1]:
import numpy as np

In [2]:
a=np.array([23,12,3,45,67,77,78,90,12,13,45,67,78,90,99,900,56,78])

In [3]:
np.mean(a)

np.float64(101.83333333333333)

In [4]:
np.median(a)

np.float64(67.0)

In [5]:
np.var(a)

np.float64(38371.13888888888)

In [6]:
np.std(a)

np.float64(195.88552496008705)

In [8]:
range=np.max(a)-np.min(a)

In [9]:
range

np.int64(897)

In [10]:
lst1=[3,4,5,6,7,8,9]
lst2=[10,23,34,67,99]

In [13]:
def mean(lst):
    sum=0
    for i in lst:
        sum=sum+i
    return sum/(len(lst))
lst1=[3,4,5,6,7,8,9]
mean(lst1)

6.0

In [14]:
lst=["happy","happy","unhappy","happy","unhappy"]

In [17]:
def mode(lst):
    count1=0
    count2=0
    for i in lst:
        if i=="happy":
            count1+=1
        else:
            count2+=1
        print("happy ",count1)
        print("unhappy ",count2)

In [18]:
mode(lst)

happy  1
unhappy  0
happy  2
unhappy  0
happy  2
unhappy  1
happy  3
unhappy  1
happy  3
unhappy  2


In [19]:
lst=["happy", "happy","unhappy","happy","unhappy"] #find out its mode
def mode(lst):
    count1=0
    count2=0
    for i in lst:
        if i=="happy":
            count1+=1
        else:
            count2+=1
    if count1>count2:
        print("happy ",count1)
    else:
        print("unhappy ",count2)
mode(lst)

happy  3


In [20]:
aa=np.array([10,20,34,56,77,37,89,90])

In [21]:
meu=np.mean(aa)

In [25]:
res=np.sum(((meu-aa)**2))/len(aa)

In [26]:
res

np.float64(848.734375)

In [27]:
sd=np.sqrt(res)

In [28]:
sd

np.float64(29.133046098889146)

In [29]:
np.percentile(aa,90)

np.float64(89.3)

In [30]:
np.percentile(aa,75)

np.float64(80.0)

In [31]:
aaa=np.array([0,0,0,0,0,0,1,1,1,1,1,1])

In [32]:
aaa.shape

(12,)

In [38]:
aaa.reshape(3,4).ndim

2

In [34]:
aaa.reshape(6,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [35]:
aaa.reshape(2,6)

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]])

In [39]:
aaa.reshape(2,2,3).ndim

3

In [37]:
aaa.reshape(2,1)

ValueError: cannot reshape array of size 12 into shape (2,1)

In [40]:
aaa.reshape(1,1,12)

array([[[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]])

In [41]:
aaa.reshape(3,2,2)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [42]:
aaa.reshape(1,1,1,12)

array([[[[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]]])

In [43]:
aa1=np.array([[1,2,3],[4,5,6],[9,8,7]])

In [44]:
aa1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [48]:
#RMO
aa1.flatten()

array([1, 2, 3, 4, 5, 6, 9, 8, 7])

In [49]:
#CMO
aa1.flatten(order='F')

array([1, 4, 9, 2, 5, 8, 3, 6, 7])