In [1]:
def matrix_Addition(m1,m2):
    c=[[0,0],[0,0]]
    for i in range(0,len(m1)):
        for j in range(0,len(m1[0])):
            c[i][j]=m1[i][j]+m2[i][j]
    return c
m1=[[1,2],[3,4]]
m2=[[1,2],[3,4]]
matrix_Addition(m1,m2)
            

[[2, 4], [6, 8]]

In [2]:
m1=[[1,2],[3,4]]
m2=[[1,2],[3,4]]

In [3]:
m1+m2

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [4]:
import numpy as np

In [5]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[1,2],[3,4]])

In [6]:
m1+m2

array([[2, 4],
       [6, 8]])

In [7]:
lst=[3,4,5,6,7,8]

In [8]:
lst+2

TypeError: can only concatenate list (not "int") to list

In [9]:
lst+[2]

[3, 4, 5, 6, 7, 8, 2]

In [10]:
a=np.array([3,4,5,6,7,8])

In [11]:
a+2

array([ 5,  6,  7,  8,  9, 10])

In [12]:
import numpy as np

In [13]:
a=np.array([2,3,4,5,6])

In [14]:
a

array([2, 3, 4, 5, 6])

In [15]:
a.ndim

1

In [16]:
aa=np.array([[1,2],[3,4]])

In [17]:
aa

array([[1, 2],
       [3, 4]])

In [18]:
aa.ndim

2

In [19]:
aaa=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [20]:
aaa

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a2=np.arange(1,10,1)

In [23]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a3=np.arange(0,10,2)

In [25]:
a3

array([0, 2, 4, 6, 8])

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
# it is giving the random values as per the uniform distribution
np.random.rand(5)

array([0.35033389, 0.98303224, 0.03465891, 0.50438986, 0.81579724])

In [35]:
#it is giving the value as per standard normal variate
np.random.randn(5)

array([-1.68669063, -0.47742998, -0.72941181, -1.81560559,  0.8783543 ])

In [36]:
b=np.array([3,4,5,6,7,8])

In [38]:
b+1

array([4, 5, 6, 7, 8, 9])

In [39]:
b**2

array([ 9, 16, 25, 36, 49, 64])

In [40]:
b/2

array([1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [41]:
b//2

array([1, 2, 2, 3, 3, 4])

In [42]:
b%2

array([1, 0, 1, 0, 1, 0])

In [43]:
a1=np.array([2,3,4,5,6,7])
a2=np.array([3,4,5,6,7,8])

In [44]:
a1>a2

array([False, False, False, False, False, False])

In [45]:
a1==a2

array([False, False, False, False, False, False])

In [46]:
a1 and a2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
a1&a2

array([2, 0, 4, 4, 6, 0])

In [48]:
np.log(a1)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015])

In [49]:
a1

array([2, 3, 4, 5, 6, 7])